server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testrest
    username: user
    password: password
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    com:
      testrest:
        tesrest:
          util:
            NumRequestLoggingFilter: DEBUG
  pattern:
    console: "{%X{requestId}} | %d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %msg - %logger{36} [%M:%L] %n"
# %-15()
# logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
